version: '3.8'

services:
  app:
    build:
      context: .  # Mudando o contexto para a raiz do projeto
      dockerfile: ./containers/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    mem_limit: 8G
    mem_reservation: 6G
    volumes:
      - .:/var/www/html/:delegated
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - mysql
    networks:
      - app-network
    command: ["php-fpm"]
    entrypoint: >
      sh -c "
      if ! command -v laravel > /dev/null; then
        curl -fsSL https://php.new/install/linux/8.4 | bash;
      fi &&
      php-fpm
      "
    
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:delegated
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-db
    env_file:
      - ./containers/mysql/.env
    volumes:
      - ./containers/mysql/volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    mem_limit: 4G
    mem_reservation: 4G
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
