name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/lab-laravel

jobs:
  validation:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar JQ (para ler composer.json)
        run: sudo apt-get install -y jq

      - name: Obter versão do composer.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' composer.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: validation

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar docker-compose
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build da imagem Docker
        run: |
          docker build -t lab-laravel:latest ./containers/php

      - name: Tag da imagem com versão e latest
        run: |
          VERSION=${{ needs.validation.outputs.version }}
          docker tag lab-laravel:latest ${{ env.IMAGE_NAME }}:$VERSION
          docker tag lab-laravel:latest ${{ env.IMAGE_NAME }}:latest

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Logar no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push das imagens
        run: |
          VERSION=$(jq -r '.version' composer.json)
          docker push ${{ env.IMAGE_NAME }}:$VERSION
          docker push ${{ env.IMAGE_NAME }}:latest
