name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Logar no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Install docker-compose
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker image
        run: |
          docker build -t lab-laravel:latest ./containers/php

      - name: Build services
        run: |
          docker-compose build

      - name: Tag da imagem
        run: |
          docker tag lab-laravel ${{ secrets.DOCKER_USERNAME }}/lab-laravel:latest

      - name: Push da imagem
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lab-laravel:latest
