name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Logar no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build da imagem com docker-compose
        run: |
          docker-compose up -d --build

      - name: Tag da imagem
        run: |
          docker tag lab-laravel ${{ secrets.DOCKER_USERNAME }}/lab-laravel:latest

      - name: Push da imagem
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lab-laravel:latest
